// <auto-generated />
using FleetDepot.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetDepot.Dal.Migrations
{
    [DbContext(typeof(FleetDepotDb))]
    partial class FleetDepotDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FleetDepot.Types.Models.Vehicle", b =>
                {
                    b.Property<string>("Series")
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("Number")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("NumberOfPassengers")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Series", "Number");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
